```
# add user
# https://www.elastic.co/guide/en/elasticsearch/reference/current/users-command.html
https://www.cnblogs.com/reblue520/p/11460584.html




---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch
    role: master
  name: elasticsearch-master
spec:
  replicas: 1
  serviceName: elasticsearch-master
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      restartPolicy: Always
      containers:
        - name: elasticsearch-master
          image: registry.cn-beijing.aliyuncs.com/app-and-cluster/elasticsearch
          imagePullPolicy: Always
          command:
            - /bin/sh
            - '-c'
            - >-
              /usr/bin/sudo sysctl -w
              vm.max_map_count=655360;/opt/app/elasticsearch-7.2.1/bin/elasticsearch;
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9200
              protocol: TCP
          env:
            - name: cluster.name
              value: "merp_es_cluster"
            - name: node.master
              value: "true"
            - name: node.data
              value: "false"
            - name: discovery.seed_hosts 
              value: "elasticsearch-discovery" 
            - name: cluster.initial_master_nodes 
              value: "elasticsearch-master-0,elasticsearch-master-1" 
            - name: node.ingest
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /opt/app/elasticsearch-7.2.1/data
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gfs
              
---
kind: Service
apiVersion: v1
metadata:
 labels:
   app: elasticsearch
 name: elasticsearch-master-discovery
spec:
 ports:
   - port: 9300
     targetPort: 9300
 selector:
   app: elasticsearch
   role: master
---
apiVersion: v1
kind: Service
metadata:
 name: elasticsearch-data-service
 labels:
   app: elasticsearch
   role: data
spec:
 ports:
   - port: 9200
     name: out
   - port: 9300
     name: in
 clusterIP: None
 selector:
   app: elasticsearch
   role: data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch
    role: master
  name: elasticsearch-data
spec:
  replicas: 2
  serviceName: elasticsearch-data
  selector:
    matchLabels:
      app: elasticsearch
      role: data
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data
    spec:
      restartPolicy: Always
      containers:
        - name: elasticsearch-data
          image: registry.cn-beijing.aliyuncs.com/app-and-cluster/elasticsearch
          imagePullPolicy: Always
          command:
            - /bin/sh
            - '-c'
            - >-
              /usr/bin/sudo sysctl -w
              vm.max_map_count=655360;/opt/app/elasticsearch-7.2.1/bin/elasticsearch;
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: cluster.name
              value: "merp_es_cluster"
            - name: node.master
              value: "fasle"
            - name: node.data
              value: "true"
            - name: discovery.seed_hosts # 
              value: "elasticsearch-master-discovery" 
            - name: cluster.initial_master_nodes 
              value: "elasticsearch-master-0,elasticsearch-master-1" 
            - name: node.ingest
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g" 
		      resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /opt/app/elasticsearch-7.2.1/data
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gfs
